name: Build docker image on tag creation

on:
  push:
    tags:
      - "**"

jobs:
  build:
    name: Build and push Image to ghcr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install dependencies
        run: yarn & yarn build
      - name: Setup Docker buildX
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{runner.os}}-buildx-${{github.sha}}
          restore-keys: |
            ${{runner.os}}-buidx-
      - name: Log in to Github Container Registry
        run: echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u USERNAME --password-stdin
      - name: Build Static Content
        run:
      - name: Build and Push Image
        id: docker-build
        uses: docker/build-push-action@v5
        env:
          IMAGE_TAG: ${{github.ref_name}}
        with:
          file: ./.docker/Dockerfile
          push: true
          tags: |
            "ghcr.io/sparcs-kaist/zabo-server:${{ env.IMAGE_TAG }}"
            "ghcr.io/sparcs-kaist/zabo-server:latest"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Remove old cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
